### PR TITLE
Update environment.yml

### PR DESCRIPTION
**Pull request by DIOUFY7**

### CODE REVIEW

**Comment by frcaud** [comment]
Hello @DIOUFY7. Lightgbm is already in environment.yml (PR#9) and it can be installed with conda so no need to add it again in the pip section of the file.

**Comment by DIOUFY7** [comment]
Hello @frcaud , i have an other error and i thought it was about that. you have here the error
image

**Comment by frcaud** [comment]
Can it be related to 'numba' library ?

Edit: I reproduced this error locally and fixed it with a reinstall of numba

**Comment by frcaud** [comment]
Numba library has been reinstalled on server.
You can try to post your submission again.
If it works, please modifiy this PR adding numba to env files.

**Pull request merged**
